package com.bank.repository;
//Fionn
//Collection of Objects
//save it or fetch
//Read or write

import java.util.List;

import com.bank.entity.Operation;
import com.bank.entity.Transaction;

import com.bank.exceptions.RepositoryException;

public class TransactionRepository implements Repository<Transaction> {
    public List<Transaction> getAll() throws RepositoryException {
        return null;
    }
	public Transaction getById(long id) throws RepositoryException {
        return null;
    }
	public Transaction save(long id, Transaction transaction) throws RepositoryException{
        return null;
    }
	public Transaction delete(long id) throws RepositoryException{
        return null;
    }
    //private static long nextId = 0;
    

    //Below auto-generated by VS Studio
    @Override
    public long count() throws RepositoryException {
        // TODO Auto-generated method stub
        return 0;
    }
    @Override
    public List<Transaction> findAll() throws RepositoryException {
        // TODO Auto-generated method stub
        return null;
    }
    @Override
    public Transaction findById(long id) throws RepositoryException {
        // TODO Auto-generated method stub
        return null;
    }
    @Override
    public Operation save(Transaction entity) throws RepositoryException {
        // TODO Auto-generated method stub
        return null;
    }




    
}
